### PR TITLE
Add phone documentation

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

``` bash
./rebuild-docs
./run
```

Go to <http://127.0.0.1:8007>, see the link to phone docs, click it, click around, check things work. If they don't, blame @pmahnke ;)

### CODE REVIEW

**Comment by anthonydillon** [comment]
QA issues from a quick click about:
- Images missing from http://127.0.0.1:8007/phone/en/apps/html-5/guides-html5-guide
- Navigation links to http://127.0.0.1:8007/phone/en/devices/installing-devices which 404s
- On http://127.0.0.1:8007/phone/en/devices/porting-new-device the link in the toc to "Need help? Get in touch" doesn't work as the id contains the ? and the link does not
- TOC link doesn't work on http://127.0.0.1:8007/phone/en/scopes/tutorials/prepare-your-scope-for-publication to data/.ini

**Comment by pmahnke** [comment]
@nottrobin @anthonydillon aren't these issues for https://github.com/ubuntudesign/phone-docs instead?

**Comment by nottrobin** [comment]
@pmahnke they are, but it's up to you whether they should block this PR or just go live regardless.

**Comment by anthonydillon** [comment]
They are significant issues which we may want to resolve before pushing
broken docs.

**Comment by anthonydillon** [comment]
All of the above issues are still there:
> Images missing from http://127.0.0.1:8007/phone/en/apps/html-5/guides-html5-guide
ubuntu phone documentation

> Navigation links to http://127.0.0.1:8007/phone/en/devices/installing-devices which 404s
These links are in the devices section of the navigation:
ubuntu phone documentation 1

The TOC are issues with the docs-builder but I thought it would mention them but happy to land if there is an issue on the other project for them.

**Comment by pmahnke** [comment]
@anthonydillon we don't see this image bug... the toc bug is already there and we might have a fix

I would like to publish and fix anything else later.

**Comment by anthonydillon** [comment]
Ok

**Pull request merged**
