### PR TITLE
Updated usage instructions

### PR DESCRIPTION
**Pull request by deadlight**
Updated the README with instructions for running the site, both with and without search.

### CODE REVIEW

**Comment by nottrobin** [comment]
Hmm. I'm a little wary of putting company specific instructions in the official readme of an open source project. I'll think about this and expand on it in a bit.

**Comment by nottrobin** [comment]
@deadlight Yeah so historically I'm not too fussy about the odd link to a private resource in issue comments etc., but I've tried to keep the main READMEs public-friendly. Opting instead to keep those instructions in the team wiki.

I've also historically not worried too much about search, as it's not usually a central concern for local development. But it would still be great to have it documented. Coupled to this there's the fact that this search solution hopefully won't exist for more than a few months (famous last words).

Would it be okay if or now you simply remove the "Run locally with functioning search" section? I like that you're adding `rebuild-docs` to the instructions, but would you also add one more line above it - `snap install documentation-builder`?

**Comment by nottrobin** [comment]
As discussed, could we please just update the wording to approach it from a public perspective?

**Comment by anthonydillon** [comment]
@deadlight could you take a look at this please.

**Comment by deadlight** [comment]
All requested changes made

**Pull request merged**
