### PR TITLE
Python3 and latest run script

### PR DESCRIPTION
**Pull request by nottrobin**
- Use python3 by default in local development
- Update the run script
- Build docs as part of the `./run build` phase
- Fix errors and warnings in sass file formatting
- Upgrade Travis test to use `./run` script

**NB**: As this removes the `rebuild-docs` script, the Jenkins build job will need updating to run `./run build` instead.

QA
--

``` bash
./run clean
./run  # Wait a very long time - like 10 minutes
./run test
./run serve
./run watch
```

Check everything works.

Check the Travis test passed.

### CODE REVIEW

**Comment by nottrobin** [comment]
[Update to python3 and latest run script](https://trello.com/c/D0yp2Hl7/3298-update-to-python3-and-latest-run-script)

**Comment by nottrobin** [comment]
Discovered a problem - images aren't being created properly.

**Comment by nottrobin** [comment]
Everything should now work again. I think.

**Comment by WillMoggridge** [comment]
Sorry, I added review to wrong PR.

I am going to try this one again because it got stuck earlier and my laptop fan went crazy.

**Pull request merged**
